default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snip-it-development
  # database: <%= ENV["POSTGRES_DB"] %>
  # username: <%= ENV["POSTGRES_USER"] %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  # host: <%= ENV["POSTGRES_HOST"] %>

test:
  <<: *default
  database: snip-it-test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
